### ISSUE TITLE
You have two kind of FormData packages included now...

### ISSUE THREAD

**Issue by jimmywarting** [stagas/wantwords#1]
https://github.com/stagas/wantwords/blob/fccf3818a4c883e8fea977b1947c6be2053249f0/cli.js#L10

Hi 👋  
b/c node-fetch 3.1.x is now able to decode payloads back into a FormData instance using this method
```js
import { Response } from 'node-fetch'
const { constructor: FormData } = await new Reponse(new URLSearchParams()).formData()
```
then we decided that this was a bit hacky and we opted to expose it to the user in v3.2.0 instead
so you can now do: 

```js
import('node-fetch').then(mod => {
  const { default: fetch, FormData } = mod
})
```

**Comment by stagas** [comment]
Thanks. I think it's better to expose it in its own separate module because tomorrow you might decide not to expose it so this is going to be a problem.

**Comment by jimmywarting** [comment]
> because tomorrow you might decide not to expose it so this is going to be a problem.
I don't think that will ever happen, we are dependent on a FormData class, and there is ways to get node-fetch internal formdata class in a round about way, so why wouldn't we just expose it to use it more easier? if NodeJS where to ever impl a built in FormData class, then we would just re-export it. We look at it the same way we do as for Headers, Request and the Response class

FormData is what's builds up the fetch api for what it really is

![image](https://user-images.githubusercontent.com/1148376/150552756-a048318e-8570-4850-be95-a80a1057ca06.png)

**Comment by stagas** [comment]
`fetch` is one thing, `FormData` is another. Just because `fetch` is using `FormData` isn't a case to re-export it, it's just the wrong thing to do. Publish `FormData` in a module that is kept up to date and `fetch` and `wantwords` can depend on that.
